import os
import psycopg2
import psycopg2.extras
from datetime import datetime
from typing import Optional
from flask import Flask, render_template, request, redirect, url_for, session, flash
try:
    from .config import get_config
except Exception:
    from config import get_config  # type: ignore


def get_conn():
    cfg = get_config()
    return psycopg2.connect(
        host=cfg.db_host,
        port=cfg.db_port,
        user=cfg.db_user,
        password=cfg.db_password,
        dbname=cfg.db_name,
    )


def ensure_admin_schema():
    conn = get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS admin_users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username TEXT NOT NULL UNIQUE,
                    password_hash TEXT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ
                )
                """
            )
            conn.commit()
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
            cur.execute("SELECT count(*) AS c FROM admin_users")
            c = cur.fetchone()["c"]
            if c == 0:
                try:
                    from werkzeug.security import generate_password_hash
                except Exception:
                    generate_password_hash = lambda x: x  # type: ignore
                default_user = os.getenv("ADMIN_USERNAME", "admin")
                default_pwd = os.getenv("ADMIN_INITIAL_PASSWORD", "admin123")
                cur.execute(
                    "INSERT INTO admin_users(username, password_hash) VALUES(%s,%s)",
                    (default_user, generate_password_hash(default_pwd)),
                )
                conn.commit()
    finally:
        conn.close()


def create_app():
    app = Flask(__name__, template_folder=os.path.join(os.path.dirname(__file__), "templates"))
    app.secret_key = os.getenv("FLASK_SECRET", os.getenv("ADMIN_SECRET", "dev-secret"))

    @app.before_request
    def _schema():
        ensure_admin_schema()

    def current_user() -> Optional[str]:
        return session.get("username")

    def clean_domain(s: str) -> str:
        s = (s or "").strip()
        s = s.strip("`'\"()[]<>")
        if s.endswith("/"):
            s = s[:-1]
        return s
    def _fmt_secs(v: Optional[float]) -> str:
        if v is None:
            return ""
        try:
            return f"{float(v):.3f}s"
        except Exception:
            return str(v)
    app.jinja_env.filters["secs"] = _fmt_secs

    @app.get("/")
    def index():
        if not current_user():
            return redirect(url_for("login"))
        return redirect(url_for("targets"))

    @app.get("/login")
    def login():
        return render_template("login.html")

    @app.post("/login")
    def do_login():
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "").strip()
        if not username or not password:
            flash("请填写用户名和密码")
            return redirect(url_for("login"))
        conn = get_conn()
        try:
            with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                cur.execute("SELECT id, username, password_hash FROM admin_users WHERE username=%s", (username,))
                row = cur.fetchone()
                if not row:
                    flash("用户名或密码错误")
                    return redirect(url_for("login"))
                try:
                    from werkzeug.security import check_password_hash
                    ok = check_password_hash(row["password_hash"], password)
                except Exception:
                    ok = row["password_hash"] == password
                if not ok:
                    flash("用户名或密码错误")
                    return redirect(url_for("login"))
                session["user_id"] = int(row["id"])
                session["username"] = row["username"]
                return redirect(url_for("targets"))
        finally:
            conn.close()

    @app.get("/logout")
    def logout():
        session.clear()
        return redirect(url_for("login"))

    @app.get("/password")
    def password():
        if not current_user():
            return redirect(url_for("login"))
        return render_template("change_password.html")

    @app.post("/password")
    def do_password():
        if not current_user():
            return redirect(url_for("login"))
        old_pwd = request.form.get("old_password", "") or ""
        new_pwd = request.form.get("new_password", "") or ""
        confirm = request.form.get("confirm_password", "") or ""
        if not new_pwd or new_pwd != confirm:
            flash("新密码与确认不一致")
            return redirect(url_for("password"))
        conn = get_conn()
        try:
            with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                cur.execute("SELECT id, password_hash FROM admin_users WHERE username=%s", (current_user(),))
                row = cur.fetchone()
                if not row:
                    flash("用户不存在")
                    return redirect(url_for("login"))
                try:
                    from werkzeug.security import check_password_hash, generate_password_hash
                    if not check_password_hash(row["password_hash"], old_pwd):
                        flash("旧密码错误")
                        return redirect(url_for("password"))
                    cur.execute(
                        "UPDATE admin_users SET password_hash=%s, updated_at=now() WHERE id=%s",
                        (generate_password_hash(new_pwd), int(row["id"])),
                    )
                except Exception:
                    if row["password_hash"] != old_pwd:
                        flash("旧密码错误")
                        return redirect(url_for("password"))
                    cur.execute(
                        "UPDATE admin_users SET password_hash=%s, updated_at=now() WHERE id=%s",
                        (new_pwd, int(row["id"])),
                    )
                conn.commit()
                flash("密码已更新")
                return redirect(url_for("targets"))
        finally:
            conn.close()

    def require_login():
        if not current_user():
            return redirect(url_for("login"))
        return None

    @app.get("/targets")
    def targets():
        r = require_login()
        if r:
            return r
        conn = get_conn()
        try:
            with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                cur.execute(
                    """
                    SELECT id, domain, enabled, priority, updated_at, last_scheduled_at, schedule_interval_minutes
                    FROM monitor_targets
                    ORDER BY priority DESC, id DESC
                    """
                )
                rows = cur.fetchall()
            return render_template("targets_list.html", rows=rows, user=current_user())
        finally:
            conn.close()

    @app.get("/targets/new")
    def target_new():
        r = require_login()
        if r:
            return r
        return render_template("target_form.html", item=None)

    @app.post("/targets/new")
    def target_create():
        r = require_login()
        if r:
            return r
        domain = clean_domain(request.form.get("domain") or "")
        enabled = (request.form.get("enabled") or "on") == "on"
        priority = int(request.form.get("priority") or "0")
        interval = int(request.form.get("schedule_interval_minutes") or "10")
        if not domain:
            flash("域名不能为空")
            return redirect(url_for("target_new"))
        conn = get_conn()
        try:
            with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                cur.execute("SELECT id FROM monitor_targets WHERE domain=%s", (domain,))
                exist = cur.fetchone()
                if exist:
                    flash("该域名已存在")
                    return redirect(url_for("targets"))
                cur.execute(
                    """
                    INSERT INTO monitor_targets(domain, enabled, priority, schedule_interval_minutes, updated_at)
                    VALUES(%s,%s,%s,%s,now())
                    """,
                    (domain, enabled, priority, interval),
                )
                conn.commit()
            flash("已新增检测目标")
            return redirect(url_for("targets"))
        finally:
            conn.close()

    @app.get("/targets/<int:target_id>/edit")
    def target_edit(target_id: int):
        r = require_login()
        if r:
            return r
        conn = get_conn()
        try:
            with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                cur.execute(
                    """
                    SELECT id, domain, enabled, priority, schedule_interval_minutes
                    FROM monitor_targets WHERE id=%s
                    """,
                    (target_id,),
                )
                row = cur.fetchone()
                if not row:
                    flash("目标不存在")
                    return redirect(url_for("targets"))
            return render_template("target_form.html", item=row)
        finally:
            conn.close()

    @app.post("/targets/<int:target_id>/edit")
    def target_update(target_id: int):
        r = require_login()
        if r:
            return r
        domain = clean_domain(request.form.get("domain") or "")
        enabled = request.form.get("enabled") == "on"
        priority = int(request.form.get("priority") or "0")
        interval = int(request.form.get("schedule_interval_minutes") or "10")
        if not domain:
            flash("域名不能为空")
            return redirect(url_for("target_edit", target_id=target_id))
        conn = get_conn()
        try:
            with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                cur.execute("SELECT id FROM monitor_targets WHERE domain=%s AND id<>%s", (domain, target_id))
                exist = cur.fetchone()
                if exist:
                    flash("该域名已存在")
                    return redirect(url_for("target_edit", target_id=target_id))
                cur.execute(
                    """
                    UPDATE monitor_targets
                    SET domain=%s, enabled=%s, priority=%s, schedule_interval_minutes=%s, updated_at=now()
                    WHERE id=%s
                    """,
                    (domain, enabled, priority, interval, target_id),
                )
                conn.commit()
            flash("已更新检测目标")
            return redirect(url_for("targets"))
        finally:
            conn.close()

    @app.get("/results")
    def results_search():
        r = require_login()
        if r:
            return r
        return render_template("results_search.html", rows=None, task=None)

    @app.post("/results")
    def results_query():
        r = require_login()
        if r:
            return r
        domain = clean_domain(request.form.get("domain") or "")
        if not domain:
            flash("请输入域名")
            return render_template("results_search.html", rows=None, task=None)
        conn = get_conn()
        try:
            with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                cur.execute(
                    "SELECT id, domain, created_at, status FROM monitor_tasks WHERE domain=%s AND status<>'running' ORDER BY created_at DESC LIMIT 1",
                    (domain,),
                )
                task = cur.fetchone()
                if not task:
                    flash("没有已完成的检测记录")
                    return render_template("results_search.html", rows=None, task=None, q_domain=domain)
                cur.execute(
                    """
                    SELECT operator, region, download_time, connect_time, dns_time, total_time,
                           status_code, ip_location, response_ip, ip_country, ip_province, ip_city, ip_isp
                    FROM monitor_results
                    WHERE task_id=%s
                    ORDER BY id ASC
                    """,
                    (int(task["id"]),),
                )
                rows = cur.fetchall()
                total_nodes = len(rows)
                status_counts = {}
                for r in rows:
                    s = str(r.get("status_code") or "--").strip()
                    status_counts[s] = status_counts.get(s, 0) + 1
                def _num(v):
                    try:
                        return float(v) if v is not None else None
                    except Exception:
                        return None
                times = [(_num(r.get("total_time")), r) for r in rows]
                times_valid = [(t, r) for t, r in times if t is not None]
                times_sorted = sorted(times_valid, key=lambda x: x[0])
                fast5 = [r for _, r in times_sorted[:5]]
                slow5 = [r for _, r in reversed(times_sorted[-5:])]
                avg_total = None
                if times_valid:
                    avg_total = sum(t for t, _ in times_valid) / len(times_valid)
                return render_template(
                    "results_search.html",
                    rows=rows,
                    task=task,
                    q_domain=domain,
                    total_nodes=total_nodes,
                    status_counts=sorted(status_counts.items(), key=lambda x: x[0]),
                    fast5=fast5,
                    slow5=slow5,
                    avg_total=avg_total,
                )
        finally:
            conn.close()

    return app


if __name__ == "__main__":
    app = create_app()
    port = int(os.getenv("PORT", "8000"))
    app.run(host="0.0.0.0", port=port, debug=True)
