services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: domainmonitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1313575799"
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  producer:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      TZ: Asia/Shanghai
    command: python task_producer/producer.py --batch-size 100 --loop-seconds 120
    volumes:
      - ./screenshots:/app/screenshots
      - ./:/app/
  worker:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      TZ: Asia/Shanghai
    command: python task_worker/worker.py --batch-size 5 --lease-minutes 15 --poll-seconds 10 --headless
    volumes:
      - ./screenshots:/app/screenshots
      - ./:/app/
volumes:
  db_data:
